#!/bin/sh

weather=$(curl -s wttr.in/Kathmandu?format=2)

if [ $(echo "$weather" | grep -E "(Unknown|curl|HTML)" | wc -l) -gt 0 ]; then
    echo "WEATHER UNAVAILABLE"
else
    echo "$weather" | awk '{printf $2" " $3}'
fi
