-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Decoration Settings

-- Hyprland Wiki Links

-- Animation - https://wiki.hyprland.org/Configuring/Animations/

-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Sourcing colors generated by wallust

require("WallustColors") -- sets color0..color15/background/foreground globals (generated by wallust)

hl.config({
    general = {
        border_size = 2,
        gaps_in = 3,
        gaps_out = 6,
            ["col.active_border"]   = color12,
            ["col.inactive_border"] = color10,
    },
})

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        -- Was 1.17, which is outside the valid 0.0-1.0 range and was read back
        -- verbatim by `hyprctl getoption decoration:inactive_opacity`. Set to 1.0
        -- rather than something lower on purpose: a global sub-1.0 inactive
        -- opacity would make EVERY unfocused app translucent, not just terminals.
        -- Terminals get their own opacity from the opacity_terminal rule in
        -- WindowRules.lua, and dim_inactive below provides the focus cue.
        inactive_opacity = 1.0,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.8,
        shadow = {
            enabled = true,
            range = 3,
            render_power = 1,
            color = color12,
            color_inactive = color10,
        },
        blur = {
            enabled = true,
            size = 10,
            passes = 2,
            -- Blur is applied regardless of the window's opacity, so a window
            -- with opacity 0.9 can still be frosted rather than clearly see-through.
            ignore_opacity = true,
            new_optimizations = true,
            -- `special` = blur behind the SPECIAL WORKSPACE, i.e. the scratchpad the
            -- dropdown terminal lives in. It is NOT an "only blur special windows"
            -- flag. Hyprland documents it as expensive and it defaults to false;
            -- set to true here on purpose. Flip it live to compare:
            --   hyprctl eval "hl.config({decoration={blur={special=false}}})"
            special = true,
            popups = true,
        },
    },
})

hl.config({
    group = {
        ["col.border_active"] = color12,
        groupbar = {
            ["col.active"] = color12,
            height = 1,
            indicator_height = 10,
            text_offset = -5,
            font_size = 13,
        },
    },
})
