-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more variable settings

-- These configs are mostly for laptops. This is addemdum to Keybinds.conf

local mainMod = "SUPER"

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

-- For disabling Touchpad. hyprctl devices to get device name.
-- NOTE: on this machine `hyprctl devices` reports no touchpads at all, so the
-- hl.device() rule below matches nothing and xf86TouchpadToggle is never
-- emitted. Kept because this file is shared with other machines.

local Touchpad_Device = "asue1209:00-04f3:319f-touchpad"

hl.bind("xf86KbdBrightnessDown", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/BrightnessKbd.sh --dec"))

-- decrease keyboard brightness

hl.bind("xf86KbdBrightnessUp", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/BrightnessKbd.sh --inc"))

-- increase keyboard brightness

hl.bind("xf86Launch1", hl.dsp.exec_cmd("rog-control-center"))

-- ASUS Armory crate button

hl.bind("xf86Launch3", hl.dsp.exec_cmd("asusctl led-mode -n"))

-- FN+F4 Switch keyboard RGB profile 

hl.bind("xf86Launch4", hl.dsp.exec_cmd("asusctl profile -n"))

-- FN+F5 change of fan profiles (Quite, Balance, Performance)

hl.bind("xf86MonBrightnessDown", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Brightness.sh --dec"))

-- decrease monitor brightness

hl.bind("xf86MonBrightnessUp", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Brightness.sh --inc"))

-- increase monitor brightness

-- The script reads the device name from the environment. This bind has to
-- export it explicitly: a Lua `local` is invisible to the child process,
-- which is why the old toggle was a silent no-op.
hl.bind("xf86TouchpadToggle", hl.dsp.exec_cmd("TOUCHPAD_ENABLED='" .. Touchpad_Device .. "' " .. os.getenv("HOME") .. "/.config/hypr/scripts/TouchPad.sh"))

-- disable touchpad

-- Screenshot keybindings using F6 (no PrinSrc button)

hl.bind(mainMod .. " + " .. "F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --now"))

-- screenshot

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --area"))

-- screenshot (area)

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --in5"))

-- # screenshot (5 secs delay)

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --in10"))

-- screenshot (10 secs delay)

hl.bind("ALT" .. " + " .. "F6", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --active"))

-- screenshot (active window only)

hl.device({
    name = Touchpad_Device,
    enabled = true,
})
