-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Commands and Apps to be executed at launch (vendor defaults)

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

local UserScripts = os.getenv("HOME") .. "/.config/hypr/scripts"

local wallDIR = os.getenv("HOME") .. "/Pictures/wallpapers"

local lock = os.getenv("HOME") .. "/.config/hypr/scripts/LockScreen.sh"

local SwwwRandom = os.getenv("HOME") .. "/.config/hypr/scripts/WallpaperAutoChange.sh"

local livewallpaper = ""

--## wallpaper stuff ###


--exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

-- wallpaper random

--exec-once = $SwwwRandom $wallDIR # random wallpaper switcher every 30 minutes

--## Startup ###




-- Drop Down terminal


-- Polkit (Polkit Gnome / KDE)


-- starup apps



-- For ubuntu


--exec-once = ags

--exec-once = blueman-applet

--exec-once = rog-control-center


-- exec-once = qs -c overview  # Quickshell Overview #MODIFIED




-- Clipboard manager



-- Rainbow borders


-- hypridle for hyprlock


-- Resume Hyprsunset if state is "on" from previous session


-- Here are list of features available but disabled by default

-- Persistent wallpaper

-- exec-once = awww-daemon --format xrgb && awww img $HOME/Pictures/wallpapers/mecha-nostalgia.png 

-- Gnome polkit for NixOS

--exec-once = $scriptsDir/Polkit-NixOS.sh

-- xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)

--exec-once = $scriptsDir/PortalHyprland.sh


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon --format xrgb")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeybindsLayoutInit.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    -- nm-tray is not installed: network-manager-applet ships only nm-applet.
    -- nm-applet --indicator above already provides the tray, so this line
    -- used to be a silent no-op failure on every boot.
    -- waybar is supervised by systemd (waybar.service, Restart=always), so it
    -- must NOT be launched directly here or two bars will race. The explicit
    -- start is a harmless no-op if the unit is already up, and a safety net if
    -- it lost the race against WAYLAND_DISPLAY being imported above.
    hl.exec_cmd("systemctl --user start waybar.service")
    hl.exec_cmd("kdeconnectd &")
    hl.exec_cmd("kdeconnect-indicator &")
    hl.exec_cmd("normcap --background-mode")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/RainbowBorders.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Hyprsunset.sh init")
    hl.exec_cmd("blueman-applet")
    -- Re-apply GPUPowerMizerMode=2 (adaptive) from ~/.nvidia-settings-rc.
    -- Without this the setting is lost on reboot, since the rc file is only
    -- read by nvidia-settings when it runs.
    hl.exec_cmd("nvidia-settings -l 2>/dev/null")
end)
