-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Default settings

-- This is where you put your own settings as this will not be touched during update 

-- if the upgrade.sh is used.

-- refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

-- NOTE: some settings are in ~/.config/hypr/configs/UserDecorAnimations.conf

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

hl.config({
    dwindle = {
        --  pseudotile = true
        preserve_split = true,
        smart_split = false,
        special_scale_factor = 0.8,
    },
})

hl.config({
    master = {
        new_status = "master",
        new_on_top = 1,
        mfact = 0.5,
    },
})

hl.config({
    general = {
        resize_on_border = true,
        layout = "dwindle",
    },
})

hl.config({
    input = {
        kb_layout = "us",
        repeat_rate = 50,
        repeat_delay = 300,
        sensitivity = 0.4,
        --mouse sensitivity
        accel_profile = "adaptive",
        -- flat or adaptive or blank or EMPTY means libinput’s default mode
        numlock_by_default = true,
        left_handed = false,
        follow_mouse = 1,
        float_switch_override_focus = false,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            clickfinger_behavior = true,
            --MODIFIED
            middle_button_emulation = false,
            tap_to_click = true,
            drag_lock = false,
            -- sensitivity = 0.4
            -- accel_profile = adaptive
        },
        -- below for devices with touchdevice ie. touchscreen
        touchdevice = {
            enabled = true,
        },
        -- below is for table see link above for proper variables
        tablet = {
            transform = 0,
            left_handed = 0,
        },
    },
})

hl.config({
    gestures = {
        workspace_swipe_distance = 500,
        workspace_swipe_invert = true,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
        workspace_swipe_create_new = true,
        workspace_swipe_forever = true,
        workspace_swipe_use_r = true,
        --uncomment if wanted a forever create a new workspace with swipe right
        --MODIFIED
        -- gesture = 3, up, dispatcher, exec, $scriptsDir/OverviewToggle.sh 
        -- gesture = 4, down, dispatcher, exec, hyprctl dispatch togglefloating && sleep 0.1 && hyprctl dispatch centerwindow
    },
})
hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "horizontal",
    ["action"] = "workspace",
})
hl.gesture({
    ["fingers"] = 2,
    ["direction"] = "pinchin",
    ["action"] = "cursorZoom",
})
hl.gesture({
    ["fingers"] = 2,
    ["direction"] = "pinchout",
    ["action"] = "cursorZoom",
})
hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "up",
    ["action"] = function() hl.dispatch(hl.dsp.window.fullscreen({mode="maximized"})) end,
})
hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "down",
    ["action"] = function() hl.dispatch(hl.dsp.window.move({workspace="special", follow=false})) end,
})
hl.gesture({
    ["fingers"] = 4,
    ["direction"] = "left",
    ["action"] = function() hl.dispatch(hl.dsp.group.next({forward=false})) end,
})
hl.gesture({
    ["fingers"] = 4,
    ["direction"] = "right",
    ["action"] = function() hl.dispatch(hl.dsp.group.next({forward=true})) end,
})
hl.gesture({
    ["fingers"] = 4,
    ["direction"] = "up",
    ["action"] = function() hl.dispatch(hl.dsp.focus({urgent_or_last=true})) end,
})
hl.gesture({
    ["fingers"] = 4,
    ["direction"] = "down",
    ["action"] = function() hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --swappy") end,
})

hl.config({
    misc = {
        disable_hyprland_logo = false,
        --MODIFIED
        disable_splash_rendering = false,
        --MODIFIED
        vrr = 1,
        --MODIFIED
        mouse_move_enables_dpms = true,
        enable_swallow = false,
        swallow_regex = "^(kitty)$",
        focus_on_activate = false,
        initial_workspace_tracking = 0,
        middle_click_paste = true,
        --MODIFIED
        enable_anr_dialog = true,
        -- Application not Responding (ANR)
        anr_missed_pings = 15,
        -- ANR Threshold default 1 is too low
        allow_session_lock_restore = true,
        -- Prevent lockscreen crash when resume from suspend
    },
})

--opengl {

-- TODO: manual review: nvidia_anti_flicker = true

--MODIFIED

--}

hl.config({
    binds = {
        workspace_back_and_forth = false,
        --MODIFIED
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
        hide_special_on_workspace_change = true,
    },
})

--Could help when scaling and not pixelating

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
    },
})

--MODIFIED

hl.config({
    render = {
        direct_scanout = 0,
        cm_auto_hdr = 1,
        --  cm_fs_passthrough = 1
    },
})

hl.config({
    cursor = {
        sync_gsettings_theme = true,
        no_hardware_cursors = 1,
        -- change to 1 if want to disable
        enable_hyprcursor = true,
        warp_on_change_workspace = 2,
        no_warps = false,
        --MODIFIED 
    },
})

--MODIFIED

hl.config({
    quirks = {
        prefer_hdr = 1,
    },
})

hl.config({
    debug = {
        disable_logs = false,
        vfr = true,
    },
})
