-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives
---@module 'hl'

-- 0.56+ TWO SILENT FAILURES FOUND AND FIXED IN THIS FILE (2026-09-29)
--
-- 1) rule() keys its registry by `name`. A rule whose name was already
--    used is SILENTLY DISCARDED - no error, no `hyprctl configerrors` entry, and
--    only the LAST rule of a given name survives. This vendor file labelled rules
--    per category, so 105 rules shared 37 names and 68 of them never took effect
--    ("float_on" alone appeared 22 times, "tag__settings" 12, "center_on" 8).
--    The wrapper below gives every rule a unique name while keeping the readable
--    label as a prefix. Do not call rule() directly in this file.
--
-- 2) `match = { tag = "..." }` is accepted but NEVER MATCHES in 0.56 - tag is an
--    ACTION (tag +name), not a matcher. Verified with a real window: it received
--    tags:["CheatSheet*"] yet none of the tag-matched float/center/size rules
--    fired. Every rule matching on a tag was therefore dead weight, so all 69 of
--    them (48 tag assignments + 21 tag matches) were removed rather than
--    rewritten. The surviving 36 rules match on class/title/fullscreen.
--
-- If per-app opacity/float/size by category is wanted back, those rules have to
-- be written against the class or title directly, not against a tag.
local RULE_SEQ = 0
local function rule(spec)
    RULE_SEQ = RULE_SEQ + 1
    spec.name = string.format("%s#%d", tostring(spec.name or "rule"), RULE_SEQ)
    return hl.window_rule(spec)
end

-- Vendor defaults for window rules and layerrules
-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- NOTES: This is only for Hyprland > 0.52.1
-- note for ja: This should NOT be implemented on Debian and Ubuntu

-- Some special override rules
-- NOTE: the original had `no_blur on` here; hyprconf2lua dropped the body.
-- The matcher is also changed from `tag` to the class, because 0.56 silently
-- ignores `match.tag`. This rule is live now that every name is unique.
rule({
    name  = "no_blur_on",
    match = {
        class = "^([Mm]pv|vlc)$",
    },
    no_blur = true,
})

rule({
    name  = "center_on",
    match = {
        class = "([Tt]hunar)",
        title = "negative:(.*[Tt]hunar.*)",
    },
    center = true,
})

rule({
    name  = "center_on",
    match = {
        title = "^(ROG Control)$",
    },
    center = true,
})

rule({
    name  = "center_on",
    match = {
        title = "^(Keybindings)$",
    },
    center = true,
})

rule({
    name  = "center_on",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    center = true,
})

rule({
    name  = "center_on",
    match = {
        class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    center = true,
})

rule({
    name  = "center_on",
    match = {
        class = "^([Ff]erdium)$",
    },
    center = true,
})

rule({
    name  = "move_72__7_",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    move = { "72%", "7%" },
})

-- windowrule to avoid idle for fullscreen apps
-- NOTE: body was dropped by hyprconf2lua. idle_inhibit is a STRING field in the
-- lua API; valid modes are 'fullscreen', 'always', 'none' (a bare boolean is
-- rejected as "string type requires a string").
rule({
    name  = "idle_inhibit_fullscr",
    match = {
        fullscreen = true,
    },
    idle_inhibit = "fullscreen",
})

-- Disable HDR/color-management auto-switch for NON-video players only
-- Video players like mpv should be able to use HDR when appropriate
rule({
    name  = "obsidian_no_auto_hdr",
    match = { class = "^md.obsidian.Obsidian$" },
    no_auto_hdr = true,
})

rule({
    name  = "float_on",
    match = {
        class = "([Zz]oom|onedriver|onedriver-launcher)",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "(org.gnome.Calculator)",
        title = "(Calculator)",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "^(mpv|com.github.rafostar.Clapper)$",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "^([Qq]alculate-gtk)$",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "^([Ff]erdium)$",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

-- windowrule - ######### float popups and dialogue #######

rule({
    name  = "float_on",
    match = {
        title = "^(Authentication Required)$",
    },
    float = true,
    center = true,
})

rule({
    name  = "float_on",
    match = {
        class = "(codium|codium-url-handler|VSCodium)",
        title = "negative:(.*codium.*|.*VSCodium.*)",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$",
        title = "negative:(Heroic Games Launcher)",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "^([Ss]team)$",
        title = "negative:^([Ss]team)$",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        class = "([Tt]hunar)",
        title = "negative:(.*[Tt]hunar.*)",
    },
    float = true,
})

rule({
    name  = "float_on",
    match = {
        title = "^(Add Folder to Workspace)$",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
    center = true,
})

rule({
    name  = "float_on",
    match = {
        title = "^(Save As)$",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
    center = true,
})

rule({
    name  = "float_on",
    match = {
        initial_title = "(Open Files)",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
})

rule({
    name  = "float_on",
    match = {
        title = "^(SDDM Background)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.16)", "(monitor_h*0.12)" },
})

-- YAD dialog for wallpaper confirmation

rule({
    name  = "float_on",
    match = {
        class = "^(yad)$",
        title = "^(YAD)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.2)", "(monitor_h*0.2)" },
})

rule({
    name  = "opacity_0_8_0_7",
    match = {
        class = "^(gedit|org.gnome.TextEditor|mousepad)$",
    },
    opacity = "0.8 0.7",
})

rule({
    name  = "opacity_0_9_0_8",
    match = {
        class = "^(deluge)$",
    },
    opacity = "0.9 0.8",
})

rule({
    name  = "opacity_0_9_0_8",
    match = {
        class = "^(seahorse)$",
    },
    opacity = "0.9 0.8",
})

rule({
    name  = "opacity_0_95_0_75",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    opacity = "0.95 0.75",
})

rule({
    name  = "size__monitor_w_0_6_",
    match = {
        class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

rule({
    name  = "size__monitor_w_0_6_",
    match = {
        class = "^([Ff]erdium)$",
    },
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

-- PINNING

rule({
    name  = "pin_on",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    pin = true,
    -- NOTE: body was dropped by hyprconf2lua; restored from `keepaspectratio on`.
    keep_aspect_ratio = true,
})

-- This not gonna take the focus to the window that appears when hovering over some of the parts of the IntelliJ Products

rule({
    name  = "no_initial_focus_on",
    match = {
        class = "^(jetbrains-*)",
    },
    -- TODO: review rule: "no_initial_focus on"
})

rule({
    name  = "no_initial_focus_on",
    match = {
        title = "^(wind.*)$",
    },
    -- NOTE: body was dropped by hyprconf2lua. Only the LAST rule of a given name
    -- registers in 0.56, so this one is live and the jetbrains-* rule above is
    -- silently discarded. See the name-collision note at the top of this file.
    no_initial_focus = true,
})

-- LAYER RULES

hl.layer_rule({ name = "rofi-blur",        match = { namespace = "rofi" },              blur = true })

hl.layer_rule({ name = "notif-blur",       match = { namespace = "notifications" },     blur = true })

hl.layer_rule({ name = "qs-overview-blur",  match = { namespace = "quickshell:overview" }, blur = true })
hl.layer_rule({ name = "qs-overview-alpha", match = { namespace = "quickshell:overview" }, ignore_alpha = 0.5 })

-- local window rules

rule({
    name  = "float_on",
    match = {
        class = "^(yzfloat-.*)",
    },
    float = true,
})
