# /* wallust template - colors-hyprland */ 

$background = rgb(33302F)
$foreground = rgb(F2E6DD)
$color0 = rgb(575453)
$color1 = rgb(2C221F)
$color2 = rgb(2D221E)
$color3 = rgb(76503E)
$color4 = rgb(76503E)
$color5 = rgb(3F6B76)
$color6 = rgb(A48B77)
$color7 = rgb(E4D4C7)
$color8 = rgb(A0948B)
$color9 = rgb(3B2D29)
$color10 = rgb(3C2D29)
$color11 = rgb(9E6A52)
$color12 = rgb(9E6A52)
$color13 = rgb(548F9E)
$color14 = rgb(DAB99F)
$color15 = rgb(E4D4C7)
