-- Generated by nwg-displays on 2026-09-25 at 12:59:29. Do not edit manually.

hl.monitor({
    output = "desc:China Star Optoelectronics Technology Co. Ltd MNG007DA6-2 0x00006006",
    mode = "2560x1600@240.0",
    position = "0x0",
    scale = 0.9999999999999997,
    bitdepth = 10,
    cm = "hdr",
    sdrbrightness = 1.2,
    vrr = 1
})
