-- Generated by nwg-displays on 2026-08-15 at 10:54:24. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@240.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "2560x267",
    scale = 1,
    bitdepth = 10
})
