-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is a file where you put your own default apps, default search Engine etc

-- Set your default editor here uncomment and reboot to take effect.

-- NOTE, this will be automatically uncommented if you select neovim or vim to your default editor

hl.env("EDITOR", "nvim")

--default editor

-- Define preferred text editor for the Quick Settings Menu (SUPER SHIFT E)

-- script will take the default EDITOR and nano as fallback

local edit = os.getenv("EDITOR") or "nano"

-- These two are for UserKeybinds.conf & Waybar Modules

local term = "kitty"

-- Terminal

local files = "kitty -e yazi"

-- Terminal file manager (TUI)

-- Default Search Engine for ROFI Search (SUPER S)

local Search_Engine = "https://www.google.com/search?q={}"
