-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Default Keybinds

-- visit https://wiki.hyprland.org/Configuring/Binds/ for more info

-- /* ---- ✴️ Variables ✴️ ---- */  #

local mainMod = "SUPER"

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

local UserScripts = os.getenv("HOME") .. "/.config/hypr/scripts"

-- settings for User defaults apps - set your default terminal and file manager on this file

require("AppDefaults") -- must load early: defines $term/$files used by binds below

--### STANDARD ####

-- Common shortcuts MODIFIED

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("pkill rofi || true && rofi -show drun -modi drun"))

-- bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu MODIFIED

-- bindd = $mainMod, B, open default browser, exec, xdg-open "https://" #MODIFIED

-- NOT USING Quickshell MODIFIED

-- bindd = $mainMod, A, desktop overview, exec, $scriptsDir/OverviewToggle.sh # toggles quickshell or ags overview (tries QS first, falls back to AGS)

-- bindd = $mainMod, A, ags overview, exec, pkill rofi || true && ags -t 'overview' # desktop overview (if installed)

--bindd = $mainMod, A, Quickshell overview, global, quickshell:overviewToggle # desktop overview (if installed)

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd(term))

-- bindd = $mainMod, Home, file manager, exec, $files #MODIFIED

-- FEATURES / EXTRAS

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "H", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeyHints.sh"))

--MODIFIED

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "R", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Refresh.sh"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/RofiEmoji.sh"))

-- bindd = $mainMod ALT, S, web search, exec, $scriptsDir/RofiSearch.sh #MODIFIED

hl.bind(mainMod .. " + " .. "tab", hl.dsp.exec_cmd("rofi -show window"))

--MODIFIED

-- bindd = $mainMod ALT, O, toggle blur, exec, $scriptsDir/ChangeBlur.sh #MODIFIED

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/GameMode.sh"))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ChangeLayout.sh"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ClipManager.sh"))

--MODIFIED

-- bindd = $mainMod CTRL, R, rofi theme selector, exec, $scriptsDir/RofiThemeSelector.sh #MODIFIED selected theme: style-6

-- bindd = $mainMod CTRL SHIFT, R, rofi theme selector (modified), exec, pkill rofi || true && $scriptsDir/RofiThemeSelector-modified.sh #MODIFIED

hl.bind(mainMod .. " + " .. "F11", hl.dsp.window.fullscreen())

--MODIFIED

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

--MODIFIED

hl.bind(mainMod .. " + " .. "Space", hl.dsp.exec_cmd("hyprctl dispatch togglefloating && sleep 0.5 && hyprctl dispatch centerwindow"))

--MODIFIED

-- bindd = $mainMod ALT, SPACE, Float all windows, exec, hyprctl dispatch workspaceopt allfloat #MODIFIED

hl.bind("F12", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Dropterminal.sh " .. term))

--MODIFIED

-- Desktop zooming or magnifier #MODIFIED

-- bindd = $mainMod ALT, mouse_down, zoom in, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"

-- bindd = $mainMod ALT, mouse_up, zoom out, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')" 

-- Waybar / Bar related

-- bindd = $mainMod CTRL, B, toggle waybar on/off, exec, pkill -SIGUSR1 waybar #MODIFIED

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "B", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/WaybarStyles.sh"))

--MODIFIED selected: arrow, everforest

-- bindd = $mainMod ALT, B, waybar layout menu, exec, $scriptsDir/WaybarLayout.sh #MODIFIED selected: top default laptop

-- Night light toggle (Hyprsunset)

-- bindd = $mainMod, N, toggle night light, exec, $scriptsDir/Hyprsunset.sh toggle #MODIFIED

-- FEATURES / EXTRAS (custom scripts)

-- bindd = $mainMod SHIFT, M, online music, exec, $UserScripts/RofiBeats.sh #MODIFIED

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/WallpaperSelect.sh"))

--MODIFIED

-- bindd = $mainMod SHIFT, W, wallpaper effects, exec, $UserScripts/WallpaperEffects.sh #MODIFIED

-- bindd = $mainMod, W, random wallpaper, exec, $UserScripts/WallpaperRandom.sh #MODIFIED

-- bindd = $mainMod CTRL, O, toggle active window opacity, exec, hyprctl setprop active opaque toggle #MODIFIED

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "K", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeyBinds.sh"))

--MODIFIED

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "A", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Animations.sh"))

--MODIFIED

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "O", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ZshChangeTheme.sh"))

--MODIFIED

-- bindlnd = ALT_L, SHIFT_L, switch keyboard layout globally, exec, $scriptsDir/SwitchKeyboardLayout.sh #MODIFIED

-- bindlnd = SHIFT_L, ALT_L, switch keyboard layout per-window, exec, $scriptsDir/Tak0-Per-Window-Switch.sh #MODIFIED

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "C", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/RofiCalc.sh"))

-- Move current workspaces to monitors (left right up or down)

-- TO MODIFY

hl.bind(mainMod .. " + " .. "F9", hl.dsp.workspace.move({ monitor = "l" }))

hl.bind(mainMod .. " + " .. "F10", hl.dsp.workspace.move({ monitor = "r" }))

hl.bind(mainMod .. " + N", function() hl.exec_cmd("hyprctl dispatch swapactiveworkspaces") end)

-- bindd = $mainMod CTRL, F11, move workspace to up monitor, movecurrentworkspacetomonitor, u #MODIFIED

-- bindd = $mainMod CTRL, F12, move workspace to down monitor, movecurrentworkspacetomonitor, d #MODIFIED

--### SYSTEM ####

hl.bind("CTRL + ALT" .. " + " .. "Delete", hl.dsp.exec_cmd("hyprctl dispatch exit 0"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Q", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KillActiveProcess.sh"))

--MODIFIED

hl.bind("CTRL + ALT" .. " + " .. "L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/LockScreen.sh"))

--MODIFIED

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "P", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Wlogout.sh"))

--MODIFIED

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t -sw"))

--MODIFIED

-- bindd = $mainMod SHIFT, E, Quick settings menu, exec, $scriptsDir/Quick_Settings.sh #MODIFIED

-- Master Layout #MODIFIED

-- bindd = $mainMod CTRL, D, remove master, layoutmsg, removemaster

-- bindd = $mainMod, I, add master, layoutmsg, addmaster

-- NOTE: J/K bindings are set dynamically by scripts/KeybindsLayoutInit.sh and scripts/ChangeLayout.sh

-- (we intentionally do not bind them statically here to avoid conflicts across layouts)

-- bindd = $mainMod, J, cycle next, layoutmsg, cyclenext

-- bindd = $mainMod, K, cycle previous, layoutmsg, cycleprev

-- bindd = $mainMod CTRL, Return, swap with master, layoutmsg, swapwithmaster

-- Dwindle Layout #MODIFIED

--bindd = $mainMod, I, toggle split (dwindle), togglesplit

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.window.pseudo())

-- Works on either layout (Master or Dwindle)

-- bindd = $mainMod, M, set split ratio 0.3, exec, hyprctl dispatch splitratio 0.3 #MODIFIED

-- Cycle windows; if floating bring to top

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Space", hl.dsp.window.cycle_next())

--MODIFIED

hl.bind(mainMod .. " + ALT + Space", function() hl.exec_cmd("hyprctl dispatch alterzorder") end)

--MODIFIED

-- Special Keys / Hot Keys

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --inc"), { locked = true })

hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --dec"), { locked = true })

hl.bind("xf86AudioMicMute", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --toggle-mic"), { locked = true })

hl.bind("xf86audiomute", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --toggle"), { locked = true })

hl.bind("xf86Sleep", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })

hl.bind("xf86Rfkill", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/AirplaneMode.sh"), { locked = true })

-- media controls using keyboards

-- Note: original conf had xf86AudioPlayPause; Lua API requires separate keynames.
-- xf86AudioPlay and xf86AudioPause below cover the play/pause key physically.
-- Removed invalid "play" keyname that caused Unknown keysym error at boot.
hl.bind("xf86AudioPause", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --pause"), { locked = true })

hl.bind("xf86AudioPlay", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --pause"), { locked = true })

hl.bind("xf86AudioNext", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --nxt"), { locked = true })

hl.bind("xf86AudioPrev", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --prv"), { locked = true })

hl.bind("xf86audiostop", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --stop"), { locked = true })

-- Screenshot keybindings NOTE: You may need to press Fn key as well

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --now"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --area"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --in5"))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --in10"))

hl.bind("ALT" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --active"))

-- screenshot with swappy (another screenshot tool)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --swappy"))

--MODIFIED

--MODIFIED

-- Resize windows

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.resize({ x = -3, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.resize({ x = 3, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.resize({ x = 0, y = -3, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.resize({ x = 0, y = 3, relative = true }))

-- Move windows

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "J", hl.dsp.window.move({ direction = "down" }))

-- Swap windows

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "H", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "K", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "J", hl.dsp.window.swap({ direction = "down" }))

-- Group

hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())

-- Rename window title

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("~/.config/hypr/scripts/rename-window.sh"))

--MODIFIED

-- Navigate within a group

-- bindd = ALT, ), Change Group Forward, changegroupactive, f #MODIFIED

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.group.next({ forward = false }))

--MODIFIED

hl.bind(mainMod .. " + CTRL + L", function() hl.exec_cmd("hyprctl dispatch lockactivegroup toggle") end)

--MODIFIED

-- bindd = ALT, (, Change Group Back, changegroupactive, b  #MODIFIED

--MODIFIED

-- Move window into/out of group

hl.bind(mainMod .. " + " .. "comma", hl.dsp.window.move({ into_group = "left" }))

-- Move active window left into a group

hl.bind(mainMod .. " + " .. "period", hl.dsp.window.move({ into_group = "right" }))

-- Move active window right into a group

hl.bind(mainMod .. " + " .. "O", hl.dsp.window.move({ out_of_group = true }))

-- Move active window out of group

-- Move focus with mainMod + vim keys

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

--MODIFIED

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

--MODIFIED

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

--MODIFIED

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

--MODIFIED

-- Workspaces related MODIFIED

-- bindd = $mainMod, tab, next workspace, workspace, m+1 

-- bindd = $mainMod SHIFT, tab, previous workspace, workspace, m-1

-- Special workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.window.move({ workspace = "special" }))

hl.bind(mainMod .. " + U", hl.dsp.workspace.toggle_special())

-- The following mappings use the key codes to better support various keyboard layouts

-- 1 is code:10, 2 is code 11, etc

-- Switch workspaces with mainMod + [0-9] 

hl.bind(mainMod .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))

-- NOTE: code:10 = key 1

hl.bind(mainMod .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))

-- NOTE: code:11 = key 2

hl.bind(mainMod .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))

-- NOTE: code:12 = key 3

hl.bind(mainMod .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))

-- NOTE: code:13 = key 4

hl.bind(mainMod .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))

-- NOTE: code:14 = key 5

hl.bind(mainMod .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))

-- NOTE: code:15 = key 6

hl.bind(mainMod .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))

-- NOTE: code:16 = key 7

hl.bind(mainMod .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

-- NOTE: code:17 = key 8

hl.bind(mainMod .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))

-- NOTE: code:18 = key 9

hl.bind(mainMod .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

-- NOTE: code:19 = key 0

--MODIFIED

-- Move active window and follow to workspace mainMod + SHIFT [0-9]

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))

-- NOTE: code:10 = key 1

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))

-- NOTE: code:11 = key 2

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))

-- NOTE: code:12 = key 3

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))

-- NOTE: code:13 = key 4

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))

-- NOTE: code:14 = key 5

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))

-- NOTE: code:15 = key 6

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))

-- NOTE: code:16 = key 7

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

-- NOTE: code:17 = key 8

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))

-- NOTE: code:18 = key 9

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

-- NOTE: code:19 = key 0

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "bracketleft", hl.dsp.window.move({ workspace = "-1" }))

-- brackets [

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "bracketright", hl.dsp.window.move({ workspace = "+1" }))

-- brackets ]

--MODIFIED

-- Move active window to a workspace silently mainMod + CTRL [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }, { follow = false }))

-- NOTE: code:10 = key 1

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }, { follow = false }))

-- NOTE: code:11 = key 2

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }, { follow = false }))

-- NOTE: code:12 = key 3

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }, { follow = false }))

-- NOTE: code:13 = key 4

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }, { follow = false }))

-- NOTE: code:14 = key 5

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }, { follow = false }))

-- NOTE: code:15 = key 6

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }, { follow = false }))

-- NOTE: code:16 = key 7

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }, { follow = false }))

-- NOTE: code:17 = key 8

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }, { follow = false }))

-- NOTE: code:18 = key 9

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }, { follow = false }))

-- NOTE: code:19 = key 0

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "bracketleft", hl.dsp.window.move({ workspace = "-1" }, { follow = false }))

-- brackets [

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "bracketright", hl.dsp.window.move({ workspace = "+1" }, { follow = false }))

-- brackets ]

--MODIFIED

-- Scroll through existing workspaces with mainMod + scroll

-- bindd = $mainMod, mouse_down, next workspace, workspace, e+1

-- bindd = $mainMod, mouse_up, previous workspace, workspace, e-1

-- bindd = $mainMod, period, next workspace, workspace, e+1

-- bindd = $mainMod, comma, previous workspace, workspace, e-1

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- NOTE: mouse:272 = right click
