-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Vendor defaults for window rules and layerrules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- NOTES: This is only for Hyprland > 0.52.1

-- note for ja: This should NOT be implemented on Debian and Ubuntu

-- windowrule - tags - add apps under appropriate tag to use the same settings

-- browser tags

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^(chrome-.+-Default)$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^([Cc]hromium)$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^(Brave-browser(-beta|-dev|-unstable)?)$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^([Tt]horium-browser|[Cc]achy-browser)$",
    },
    tag  = "browser",
})

hl.window_rule({
    name  = "tag__browser",
    match = {
        class = "^(zen-alpha|zen)$",
    },
    tag  = "browser",
})

-- notif tags

hl.window_rule({
    name  = "tag__notif",
    match = {
        class = "^(swaync-control-center|swaync-notification-window|swaync-client|class)$",
    },
    tag  = "notif",
})

-- settings tags

hl.window_rule({
    name  = "tag__cheatsheet",
    match = {
        title = "^(Quick Cheat Sheet)$",
    },
    tag  = "CheatSheet",
})

hl.window_rule({
    name  = "tag__quicksettings",
    match = {
        title = "^(Hyprland Settings)$",
    },
    tag  = "QuickSettings",
})

hl.window_rule({
    name  = "tag__nwgsettings",
    match = {
        class = "^(nwg-displays|nwg-look)$",
    },
    tag  = "NwgSettings",
})

-- terminal tags

hl.window_rule({
    name  = "tag__terminal",
    match = {
        class = "^(Alacritty|kitty|kitty-dropterm)$",
    },
    tag  = "terminal",
})

-- email tags

hl.window_rule({
    name  = "tag__email",
    match = {
        class = "^([Tt]hunderbird|org.gnome.Evolution)$",
    },
    tag  = "email",
})

hl.window_rule({
    name  = "tag__email",
    match = {
        class = "^(eu.betterbird.Betterbird)$",
    },
    tag  = "email",
})

-- project tags

-- windowrule = match:class ^(codium|codium-url-handler|VSCodium)$, tag +projects

-- windowrule = match:class ^(VSCode|code|code-url-handler)$, tag +projects

-- windowrule = match:class ^(jetbrains-.+)$, tag +projects

-- screenshare tags

hl.window_rule({
    name  = "tag__screenshare",
    match = {
        class = "^(com.obsproject.Studio)$",
    },
    tag  = "screenshare",
})

-- IM tags

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$",
    },
    tag  = "im",
})

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^([Ff]erdium)$",
    },
    tag  = "im",
})

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^([Ww]hatsapp-for-linux)$",
    },
    tag  = "im",
})

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^(ZapZap|com.rtosta.zapzap)$",
    },
    tag  = "im",
})

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$",
    },
    tag  = "im",
})

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^(teams-for-linux)$",
    },
    tag  = "im",
})

hl.window_rule({
    name  = "tag__im",
    match = {
        class = "^(im.riot.Riot|Element)$",
    },
    tag  = "im",
})

-- game tags

hl.window_rule({
    name  = "tag__games",
    match = {
        class = "^(gamescope)$",
    },
    tag  = "games",
})

hl.window_rule({
    name  = "tag__games",
    match = {
        class = "^(steam_app_\\\\d+)$",
    },
    tag  = "games",
})

-- gamestore tags

hl.window_rule({
    name  = "tag__gamestore",
    match = {
        class = "^([Ss]team)$",
    },
    tag  = "gamestore",
})

hl.window_rule({
    name  = "tag__gamestore",
    match = {
        title = "^([Ll]utris)$",
    },
    tag  = "gamestore",
})

hl.window_rule({
    name  = "tag__gamestore",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$",
    },
    tag  = "gamestore",
})

-- file-manager tags

hl.window_rule({
    name  = "tag__file-manager",
    match = {
        class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$",
    },
    tag  = "file-manager",
})

hl.window_rule({
    name  = "tag__file-manager",
    match = {
        class = "^(app.drey.Warp)$",
    },
    tag  = "file-manager",
})

-- wallpaper tags

hl.window_rule({
    name  = "tag__wallpaper",
    match = {
        class = "^([Ww]aytrogen)$",
    },
    tag  = "wallpaper",
})

-- multimedia tags

hl.window_rule({
    name  = "tag__multimedia",
    match = {
        class = "^([Aa]udacious)$",
    },
    tag  = "multimedia",
})

-- multimedia-video tags

hl.window_rule({
    name  = "tag__multimedia_vide",
    match = {
        class = "^([Mm]pv|vlc)$",
    },
    tag  = "multimedia_video",
})

-- settings tags

hl.window_rule({
    name  = "tag__settings",
    match = {
        title = "^(ROG Control)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(wihotspot(-gui)?)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^([Bb]aobab|org.gnome.[Bb]aobab)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(gnome-disks|wihotspot(-gui)?)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        title = "(Kvantum Manager)",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(file-roller|org.gnome.FileRoller)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(nm-applet|nm-connection-editor|blueman-manager)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(qt5ct|qt6ct|[Yy]ad)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "(xdg-desktop-portal-gtk)",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    tag  = "settings",
})

hl.window_rule({
    name  = "tag__settings",
    match = {
        class = "^([Rr]ofi)$",
    },
    tag  = "settings",
})

-- viewer tags

hl.window_rule({
    name  = "tag__viewer",
    match = {
        class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$",
    },
    tag  = "viewer",
})

hl.window_rule({
    name  = "tag__viewer",
    match = {
        class = "^(evince)$",
    },
    tag  = "viewer",
})

hl.window_rule({
    name  = "tag__viewer",
    match = {
        class = "^(eog|org.gnome.Loupe)$",
    },
    tag  = "viewer",
})

-- Some special override rules

hl.window_rule({
    name  = "no_blur_on",
    match = {
        tag = "multimedia_video",
    },
    -- TODO: review rule: "no_blur on"
})

hl.window_rule({
    name  = "opacity_1_0",
    match = {
        tag = "multimedia_video",
    },
    opacity = "1.0",
})

-- POSITION

-- windowrule = match:floating true, center on

hl.window_rule({
    name  = "center_on",
    match = {
        tag = "CheatSheet",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "([Tt]hunar)",
        title = "negative:(.*[Tt]hunar.*)",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(ROG Control)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        tag = "NwgSettings",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "^(Keybindings)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "^([Ff]erdium)$",
    },
    center = true,
})

hl.window_rule({
    name  = "move_72__7_",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    move = { "72%", "7%" },
})

-- windowrule to avoid idle for fullscreen apps

hl.window_rule({
    name  = "idle_inhibit_fullscr",
    match = {
        fullscreen = true,
    },
    -- TODO: review rule: "idle_inhibit fullscreen"
})

-- FLOAT

hl.window_rule({
    name  = "float_on",
    match = {
        tag = "CheatSheet",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        tag = "wallpaper",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        tag = "settings",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        tag = "viewer",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        tag = "NwgSettings",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "([Zz]oom|onedriver|onedriver-launcher)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "(org.gnome.Calculator)",
        title = "(Calculator)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(mpv|com.github.rafostar.Clapper)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^([Qq]alculate-gtk)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^([Ff]erdium)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

-- windowrule - ######### float popups and dialogue #######

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Authentication Required)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "(codium|codium-url-handler|VSCodium)",
        title = "negative:(.*codium.*|.*VSCodium.*)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$",
        title = "negative:(Heroic Games Launcher)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^([Ss]team)$",
        title = "negative:^([Ss]team)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "([Tt]hunar)",
        title = "negative:(.*[Tt]hunar.*)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Add Folder to Workspace)$",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
    center = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(Save As)$",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
    center = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        initial_title = "(Open Files)",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "^(SDDM Background)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.16)", "(monitor_h*0.12)" },
})

-- YAD dialog for wallpaper confirmation

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(yad)$",
        title = "^(YAD)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.2)", "(monitor_h*0.2)" },
})

-- END of float popups and dialogue #######

-- OPACITY

hl.window_rule({
    name  = "opacity_0_99_0_8",
    match = {
        tag = "browser",
    },
    opacity = "0.99 0.8",
})

-- windowrule = match:tag projects, opacity 0.9 0.8

hl.window_rule({
    name  = "opacity_0_94_0_86",
    match = {
        tag = "im",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    name  = "opacity_0_94_0_86",
    match = {
        tag = "multimedia",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    name  = "opacity_0_9_0_8",
    match = {
        tag = "file-manager",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name  = "opacity_0_9_0_7",
    match = {
        tag = terminal,
    },
    opacity = "0.9 0.7",
})

hl.window_rule({
    name  = "opacity_0_8_0_7",
    match = {
        tag = "settings",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    name  = "opacity_0_82_0_75",
    match = {
        tag = "viewer",
    },
    opacity = "0.82 0.75",
})

hl.window_rule({
    name  = "opacity_0_9_0_7",
    match = {
        tag = "wallpaper",
    },
    opacity = "0.9 0.7",
})

hl.window_rule({
    name  = "opacity_0_8_0_7",
    match = {
        class = "^(gedit|org.gnome.TextEditor|mousepad)$",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    name  = "opacity_0_9_0_8",
    match = {
        class = "^(deluge)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name  = "opacity_0_9_0_8",
    match = {
        class = "^(seahorse)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    name  = "opacity_0_95_0_75",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    opacity = "0.95 0.75",
})

-- SIZE

hl.window_rule({
    name  = "size__monitor_w_0_65",
    match = {
        tag = "CheatSheet",
    },
    size = { "(monitor_w*0.65)", "(monitor_h*0.9)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_7_",
    match = {
        tag = "wallpaper",
    },
    size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_7_",
    match = {
        tag = "settings",
    },
    size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_6_",
    match = {
        class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_6_",
    match = {
        class = "^([Ff]erdium)$",
    },
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

-- PINNING

hl.window_rule({
    name  = "pin_on",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    pin = true,
    -- TODO: review rule: "keep_aspect_ratio on"
})

-- BLUR & FULLSCREEN

hl.window_rule({
    name  = "no_blur_on",
    match = {
        tag = "games",
    },
    -- TODO: review rule: "no_blur on"
    fullscreen = 0,
})

hl.window_rule({
    name  = "fullscreen_0",
    match = {
        tag = "games",
    },
    fullscreen = 0,
})

-- This not gonna take the focus to the window that appears when hovering over some of the parts of the IntelliJ Products

hl.window_rule({
    name  = "no_initial_focus_on",
    match = {
        class = "^(jetbrains-*)",
    },
    -- TODO: review rule: "no_initial_focus on"
})

hl.window_rule({
    name  = "no_initial_focus_on",
    match = {
        title = "^(wind.*)$",
    },
    -- TODO: review rule: "no_initial_focus on"
})

-- LAYER RULES

hl.layer_rule({ name = "rofi-blur",        match = { namespace = "rofi" },              blur = true })

hl.layer_rule({ name = "notif-blur",       match = { namespace = "notifications" },     blur = true })

hl.layer_rule({ name = "qs-overview-blur",  match = { namespace = "quickshell:overview" }, blur = true })
hl.layer_rule({ name = "qs-overview-alpha", match = { namespace = "quickshell:overview" }, ignore_alpha = 0.5 })

-- local window rules

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(yzfloat-.*)",
    },
    float = true,
})
