# /* wallust template - colors-kitty */

foreground         #ECE8DD
background         #0B0000
cursor             #BEB09D

active_tab_foreground     #0B0000
active_tab_background     #ECE8DD
inactive_tab_foreground   #ECE8DD
inactive_tab_background   #0B0000

active_border_color   #ECE8DD
inactive_border_color #0B0000
bell_border_color     #462E1D

color0      #0B0000
color1		#462E1D
color2		#6C5B46
color3		#376A58
color4		#718331
color5		#928770
color6		#988E76
color7		#DCD6C6
color8		#9A958A
color9		#5D3E27
color10		#90795E
color11		#498D76
color12		#97AF41
color13		#C3B495
color14		#CABD9D
color15		#DCD6C6
