#!/usr/bin/env bash
# Apply animation presets via rofi menu (Lua config, Hyprland 0.56+)
# Writes Animations.lua then reloads config to activate.

# Ensure hyprconf2lua is in PATH (installed via pipx/cargo)
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Ensure hyprctl can connect to Hyprland
if [[ -z "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
    _hypr_socket_dir=$(find /run/user/$(id -u)/hypr -maxdepth 1 -type d ! -name "hypr" 2>/dev/null | head -1)
    if [[ -n "$_hypr_socket_dir" ]]; then
        export HYPRLAND_INSTANCE_SIGNATURE="${_hypr_socket_dir##*/}"
        export HYPRLAND_SOCKET="$_hypr_socket_dir/.socket.sock"
    fi
fi
unset _hypr_socket_dir

# Check if rofi is already running
if pidof rofi > /dev/null; then
  pkill rofi
fi

# Variables
iDIR="$HOME/.config/swaync/images"
SCRIPTSDIR="$HOME/.config/hypr/scripts"
animations_dir="$HOME/.config/hypr/animations"
UserConfigs="$HOME/.config/hypr/configs"
rofi_theme="$HOME/.config/rofi/config-Animations.rasi"
msg='❗NOTE:❗ This will convert & apply animations into Animations.lua (lua mode)'
animations_list=$(find -L "$animations_dir" -maxdepth 1 -type f -name '*.conf' | sed 's/.*\///' | sed 's/\.conf$//' | sort -V)

# Rofi Menu
chosen_file=$(echo "$animations_list" | rofi -i -dmenu -config $rofi_theme -mesg "$msg")

# Check if a file was selected
if [[ -n "$chosen_file" ]]; then
    full_path="$animations_dir/$chosen_file.conf"

    if command -v hyprconf2lua >/dev/null 2>&1; then
        # Convert hyprlang .conf -> lua, remove hyprconf2lua's curve definitions
        # (we provide our own canonical curve definitions below)
        clean_code=$(hyprconf2lua "$full_path" 2>/dev/null | perl -0777 -pe 's/hl\.curve\("[^"]+",\s*\{.*?\}\s*\);//gs')

        # Replace undefined curve references (e.g., myBezier removed by perl cleanup)
        clean_code=$(echo "$clean_code" | sed 's/bezier = "myBezier"/bezier = "default"/g')
    else
        cp "$full_path" "$UserConfigs/Animations.conf"
        clean_code=""
    fi

    if [[ -n "$clean_code" ]]; then
        # Strip comments and blank lines
        clean_code=$(echo "$clean_code" | sed 's/--.*$//' | sed '/^[[:space:]]*$/d')

        # Prepend canonical curve definitions (new format)
        custom_curves=$(cat <<'CURVES'
hl.curve("wind", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("winIn", { type = "bezier", points = { {0.1, 1.1}, {0.1, 1.1} } })
hl.curve("winOut", { type = "bezier", points = { {0.3, -0.3}, {0, 1} } })
hl.curve("liner", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.curve("overshot", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.1} } })
hl.curve("smoothOut", { type = "bezier", points = { {0.5, 0}, {0.99, 0.99} } })
hl.curve("smoothIn", { type = "bezier", points = { {0.5, -0.5}, {0.68, 1.5} } })
hl.curve("md3_standard", { type = "bezier", points = { {0.12, 0}, {0, 1} } })
hl.curve("md3_decel", { type = "bezier", points = { {0.05, 0.8}, {0.1, 0.97} } })
hl.curve("md3_accel", { type = "bezier", points = { {0.2, 0}, {0.8, 0.08} } })
hl.curve("md2", { type = "bezier", points = { {0.3, 0}, {0.15, 1} } })
hl.curve("menu_decel", { type = "bezier", points = { {0.05, 0.82}, {0, 1} } })
hl.curve("menu_accel", { type = "bezier", points = { {0.2, 0}, {0.82, 0.1} } })
hl.curve("easeOutCirc", { type = "bezier", points = { {0, 0.55}, {0.45, 1} } })
hl.curve("easeOutExpo", { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("softAcDecel", { type = "bezier", points = { {0.2, 0.2}, {0.15, 1} } })
hl.curve("hyprnostretch", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
hl.curve("crazyshot", { type = "bezier", points = { {0.1, 1.5}, {0.76, 0.92} } })
hl.curve("default", { type = "bezier", points = { {0, 0}, {1, 1} } })

CURVES
        )

        clean_code="${custom_curves}${clean_code}"

        # Fix 1: inject bezier = "default" where missing
        clean_code=$(echo "$clean_code" | while IFS= read -r line; do
            if echo "$line" | grep -q 'hl\.animation' && ! echo "$line" | grep -q 'bezier'; then
                echo "$line" | sed 's/  *})$/, bezier = "default" })/'
            else
                echo "$line"
            fi
        done)

        # Fix 2: clamp values exceeding Hyprland limits
        clean_code=$(echo "$clean_code" | perl "$SCRIPTSDIR/clamp_values.pl")

        # Fix 3: propagate animations.enabled = false to individual animations
        if echo "$clean_code" | grep -q 'animations = {' && echo "$clean_code" | grep -A2 'animations = {' | grep -q 'enabled = false'; then
            clean_code=$(echo "$clean_code" | sed 's/hl\.animation({ leaf = \([^,]*\), enabled = true, speed = 0/hl.animation({ leaf = \1, enabled = false, speed = 1/g')
        fi

        # Write Animations.lua
        {
        echo "-- Generated by Animations.sh from $chosen_file"
        echo ""
        echo "$clean_code"
        } > "$UserConfigs/Animations.lua"

        # Reload Hyprland so the Lua config picks up the new Animations.lua
        hyprctl reload >/dev/null 2>&1

        notify-send -u low -i "$iDIR/ja.png" "$chosen_file" "Animation Loaded & Reloaded"
    else
        notify-send -u critical -i "$iDIR/ja.png" "$chosen_file" "Conversion failed (hyprconf2lua not found)"
    fi
fi

"$SCRIPTSDIR/RefreshNoWaybar.sh"
